apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 768;
    }

    http {
      access_log /var/log/nginx/access.log combined;
      server {
        root /usr/share/nginx/html;
        location / {
          autoindex on;
        }
      }
    }
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <title>Welcome to my Nginx Server</title>
    </head>
    <body>
      <h1>Hello, World!</h1>
      <p>This is a sample index.html file deployed with Nginx.</p>
    </body>
    </html>
