apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    app: nginx

spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx

  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: nginx-storage
        persistentVolumeClaim:
          claimName: nginx-pvc

      containers:
      - name: nginx
        image: nginx:latest
        ports:
          - containerPort: 80

        volumeMounts:
        - name: postgres-storage
          mountPath: /usr/share/nginx
          readOnly: false

        volumes:
          - name: nginx-pvc
            persistentVolumeClaim:
              claimNanme: nginx-pvc