apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections 768;
    }

    http {
      access_log /var/log/nginx/access.log combined;
      server {
        root /usr/share/nginx/html;
        location / {
          autoindex on;
        }
      }
    }
