apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: microservicios
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin/phpmyadmin:latest
        ports:
          - containerPort: 80
        env:
        - name: PMA_HOST
          value: "mysql"  # Nombre del servicio MySQL en Kubernetes
        - name: PMA_PORT
          value: "3306"
